### ISSUE TITLE
Use warnings not print

### ISSUE THREAD

**Issue by bennuttall** [lawsie/guizero#198] opened 2018-06-18 12:40 UTC
It would be neater if guizero used the [warnings](https://docs.python.org/3/library/warnings.html) module rather than print. You can suppress warnings, but you can't suppress prints.

e.g. here: https://github.com/lawsie/guizero/blob/master/guizero/utilities.py#L362:L377

**Comment by martinohanlon** [comment] 2018-06-18 14:41
thanks, closing as its a dupe of #189

**Closed by martinohanlon** 2018-06-18 14:41 UTC

**Comment by lawsie** [comment] 2018-06-18 14:47
I've already looked into this but the trouble with this is that the warnings look horrible in IDLE and kids don't read them.

e.g.
```python
warnings.warn('guizero warning: you are too orangey for crows')
```

...results in this:
<img width="392" alt="warning" src="https://user-images.githubusercontent.com/5183697/41543386-a33c3bb0-730e-11e8-9c37-926a84eff24d.png">

This is going to get ignored by most younger kids as "a load of boring error text". You could argue that they should be taught not to ignore it, or that it's IDLE's fault, but at the end of the day it's like that, and that's the way it is. Any thoughts on how to get around this would be most welcome!
