### ISSUE TITLE
Problem with the OS version

### ISSUE THREAD

**Issue by RomoloPoliti** [lawsie/guizero#400] opened 2020-12-28 10:59 UTC
**Describe the bug**
Importing the guizero lib I obtain the following error:

macOS 11 or later required !

My os version is 11.1 (tested using platform.mac_ver())

**System information:**
 - OS: MacOs 11.1
 - guizero version: 1.1.1

**Comment by martinohanlon** [comment] 2020-12-28 11:28
This looks to be an issue with how brew installs Python.

There are details here, advice is to install using the official Python installer.

https://stackoverflow.com/questions/65315077/interpreter-crashes-trying-to-use-tkinter-library

Not a bug with guizero so closing.

**Closed by martinohanlon** 2020-12-28 11:28 UTC
Labels: bug
