### ISSUE TITLE
Multiple windows operning at once 

### ISSUE THREAD

**Issue by goldenglover62** [lawsie/guizero#425] opened 2021-09-02 05:10 UTC
I have a simple login window attached to a text file which reads usernames and passwords and when the correct username and password is entered it leads towards a function that opens up another window which gives the details such as name and job status. With this I have multiple usernames and passwords and it is only picking up the first username and password and if it matches up it opens a new window for each "employee" rather then the one selected from the username and password. Im not sure what to do from here can anyone please help me out!

```
def enter():
      if login():
          app.hide()
          information()
       else:
           app.destroy()

def login():
      for line in open("database.txt", "r").readlines():
      login_info = line.split()
      un = username_input.value
      pw = password_input.value
      job = "employee"
      if un == login_info[0] and pw == login_info[1] and job = login_info[2]:
           return True
       
      return False

def information():
    for line in open("database.txt", "r").readlines():
        user_info = line.split()
        name = user_info[3]
        position = user_info[2]
        window = Window(app)
        app.hide()
        picturebox = Box(window, grid=[0, 0])
        picture = Picture(picturebox, image="major resourses/yes.png")
        info_box = Box(window, grid=[0,2])
        info_name = Text(info_box, text="name:", align="left")
        info_name1 = Text(info_box, text=name, align="left")
        position_box = Box(window, grid=[0,3])
        info_pos = Text(position_box, text="Position:", align="left")
        info_pos1 = Text(position_box, text=position, align="left")


```

this isnt the whole code but this is just the sections that relate to this question

**Comment by aajshaw** [comment] 2021-09-02 14:51
There are a few problems with the above code in that the indentation is messed up, particularly in the  login() function and the line ```if un == login_info[0] and pw == login_info[1] and job = login_info[2]:``` the final comparison should be a double equal not a single equal ```if un == login_info[0] and pw == login_info[1] and job == login_info[2]:```. 

But the main logic problem that you are reporting would appear to be caused by  the code in the information() function where for every line that is read from database.txt  a window is created that has a picture and four text elements. I suspect that there should be an ```if``` statement after line 21 ```user_info = line.split()```  and the code that creates the window be conditional upon a check against the user name. So maybe the function should look something like this:

```python
def information():
    for line in open("database.txt", "r").readlines():
        user_info = line.split()
        if username_input.value == user_info[0]:
            name = user_info[3]
            position = user_info[2]
            window = Window(app)
            app.hide()
            picturebox = Box(window, grid=[0, 0])
            picture = Picture(picturebox, image="major resourses/yes.png")
            info_box = Box(window, grid=[0,2])
            info_name = Text(info_box, text="name:", align="left")
            info_name1 = Text(info_box, text=name, align="left")
            position_box = Box(window, grid=[0,3])
            info_pos = Text(position_box, text="Position:", align="left")
            info_pos1 = Text(position_box, text=position, align="left")
            
            return
```

Without the rest of the code that you are running it will be difficult to go much further with this.

**Comment by goldenglover62** [comment] 2021-09-02 22:43
Thank you very much!

**Comment by martinohanlon** [comment] 2021-11-16 16:44
Thank you @aajshaw. Closing.

**Closed by martinohanlon** 2021-11-16 16:44 UTC
Labels: help wanted
