### ISSUE TITLE
PushButton

### ISSUE THREAD

**Issue by krakendavie** [lawsie/guizero#429] opened 2021-11-02 18:39 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System information:**
 - OS: [e.g. Debian]
 - guizero version: [Type `pip show guizero` in a terminal/command prompt]

**Additional context**
Add a
![Screenshot at 2021-11-02 21-38-08](https://user-images.githubusercontent.com/31566430/139925044-87bb4cb5-34d7-4850-b69d-2aa634e2f0e1.png)
![Screenshot at 2021-11-02 21-38-08](https://user-images.githubusercontent.com/31566430/139925090-e6f90b8b-829c-4647-9594-03ceb00f1318.png)
ny other context about the problem here.

**Comment by krakendavie** [comment] 2021-11-02 18:40
![Screenshot at 2021-11-02 21-40-18](https://user-images.githubusercontent.com/31566430/139925305-2682a65e-78ae-4eab-ae35-03bd38c798b0.png)

**Comment by bsimmo** [comment] 2021-11-02 20:46
It's not a bug, you've just not imported the PushButton in the imports.


https://lawsie.github.io/guizero/pushbutton/

**Comment by martinohanlon** [comment] 2021-11-03 09:17
As @bsimmo points out you are missing `PushButton` from your imports.

e.g.

```
from guizero import App, Text
```

should be.

```
from guizero import App, Text, PushButton
```

closing.

**Closed by martinohanlon** 2021-11-03 09:17 UTC
Labels: bug
