### ISSUE TITLE
Bind doesnt seem to work with listbox, but I can set_event

### ISSUE THREAD

**Issue by ethanpil** [lawsie/guizero#384] opened 2020-10-22 06:07 UTC
**Describe the bug**
The built in `widget.tk.bind` doesn't seem to work properly on listboxes. 
However after studing the code, if I use/abuse guizero's `set_event` it works well.
Perhaps related to #330 

After binding to the `<Double-1>` event, when I double click on a listbox entry, it should show me a popup, but it doesnt.

**To Reproduce**

This does not work:

```
from guizero import App, ListBox, info

app = App(height=415)

def xxDoubleClick():
    app.info("info", "this is a guizero app")

xx = ListBox(app, width="fill", height="fill")

for n in range(5):
    xx.append(n)

xx.tk.bind('<Double-1>', xxDoubleClick)
     
app.display()
```

This works fine:
```
from guizero import App, ListBox, info

app = App(height=415)

def xxDoubleClick():
    app.info("info", "this is a guizero app")

xx = ListBox(app, width="fill", height="fill")

for n in range(5):
    xx.append(n)

xx.events.set_event("<double_clicked>", "<Double-1>", xxDoubleClick)

app.display()
```

**Expected behaviour**
After binding to the `<Double-1>` event, when I double click on a listbox entry, it should show me a popup, but it doesnt.

**System information:**
 - OS: Windows 10
 - guizero version: 1.1.0
 - python version: 3.7

**Comment by martinohanlon** [comment] 2020-10-22 13:07
I think this relates to #366 

Could you test what happens if you bind to the internal listbox widget using:

```python
xx._listbox.tk.bind('<Double-1>', xxDoubleClick)
```

I suspect by binding to the frame you dont get the action you expect.

**Comment by ethanpil** [comment] 2020-10-22 14:36
```
from guizero import App, ListBox, info

app = App(height=415)

def xxDoubleClick():
    app.info("info", "this is a guizero app")

xx = ListBox(app, width="fill", height="fill")

for n in range(5):
    xx.append(n)

xx._listbox.tk.bind('<Double-1>', xxDoubleClick)

app.display()
```
Results in:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\***\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
TypeError: xxDoubleClick() takes 0 positional arguments but 1 was given
```

**Comment by martinohanlon** [comment] 2020-10-22 18:54
The error suggests your xDoubleClick function should accept 1 parameter. Probably the event which is occurred. e.g.

```python
def xxDoubleClick(event):
    app.info("info", "this is a guizero app")
```

**Comment by ethanpil** [comment] 2020-10-22 19:01
You are correct, I can confirm that when I add the `event` parameter it works with your code above:

```
from guizero import App, ListBox, info

app = App(height=415)

def xxDoubleClick(event):
    app.info("info", "this is a guizero app")

xx = ListBox(app, width="fill", height="fill")

for n in range(5):
    xx.append(n)

xx._listbox.tk.bind('<Double-1>', xxDoubleClick)

app.display()
```

**Comment by martinohanlon** [comment] 2020-10-22 19:05
I am going to close this issue as a duplicate of #366 

While you experienced a different issue the root cause is the same.

**Closed by martinohanlon** 2020-10-22 19:05 UTC
Labels: bug, duplicate
