### ISSUE TITLE
The grid layout is not displayed according to coordinates, more like displaying the order and size of coordinates

### ISSUE THREAD

**Issue by yingjie52** [lawsie/guizero#478] opened 2023-07-13 02:37 UTC
**Describe the bug**
The grid layout is not displayed according to coordinates, more like displaying the order and size of coordinates

**To Reproduce**
Steps to reproduce the behaviour:
from guizero import App, Text, TextBox
app = App(layout="grid")
name_label = Text(app, text="Name", grid=[0,0], align="left")
name = TextBox(app, grid=[1,0])
surname_label = Text(app, text="Surname", grid=[0,1], align="left")
surname = TextBox(app, grid=[1,1])
dob_label = Text(app, text="Date of Birth", grid=[0,2], align="left")
dob = TextBox(app, grid=[1,2])
app.display()

1. Change [0,1] to [0,5]
2. Change [1,1] to [1,5]

**Expected behaviour**
surname_label  Displayed on the fifth grid, not on the third grid；；；like excel

**Screenshots**
Due to some reasons, uploading screenshots failed；

**System information:**
 - OS: Windows
 - guizero version: 1.4.0

**Additional context**

**Comment by lawsie** [comment] 2023-07-13 05:45
I haven’t tested, but I think that this is actually working as intended,
however the grid does not behave like Excel! Any cells with no contents (ie
0,3 and 0,4 in your example) are collapsed to almost 0 width and height.

There are some more tips on layouts here:

https://lawsie.github.io/guizero/layout/

**Comment by martinohanlon** [comment] 2023-07-13 06:15
I agree @lawsie, this is working as intended. Cells are sized to fit what they contain, if they contain nothing the size of each cell will be zero.

**Comment by yingjie52** [comment] 2023-07-13 06:30
For example, if two buttons are not so close together and want to be separated by one line, how can we achieve this

**Comment by bsimmo** [comment] 2023-07-13 07:52
Having used this for a while, this was also one of the, erm, fun tasks during FutureLearn/teach computing to get your head around. (I think they're now an another learning site, I've lost track) 
I think it may also be in their book too.

**Comment by martinohanlon** [comment] 2023-11-21 08:19
Closing as wont fix.

**Closed by martinohanlon** 2023-11-21 08:19 UTC
Labels: wontfix
