### ISSUE TITLE
Image not repositioning on grid

### ISSUE THREAD

**Issue by edenhikri** [lawsie/guizero#373] opened 2020-06-18 00:35 UTC
I am trying to centre an image using grid but every time I change the grid position, the picture stays in the same position as it started in.

```
from guizero import App, Picture

app = App(title="smartKey", layout="grid", width=800, height=800)
    
logo = Picture(app, image="cat.gif", grid=[1,1])

app.display()
```

![Screen Shot 2020-06-18 at 10 35 17 am](https://user-images.githubusercontent.com/48461270/84964422-6861e400-b14f-11ea-9e9e-7f77e6c372e4.jpg)

**System information:**
 - Using macOS Catalina
 - guizero version 1.1.0

**Comment by martinohanlon** [comment] 2020-06-18 10:20
The grid will automatically resize dependant on the widgets inside the grid. So you are never going to be able to get it aligned to the middle. In summary - thats not how grids work.

Information on how to layout your gui can be found at https://lawsie.github.io/guizero/layout/

If all you are trying to do is align your image to the centre, just use the auto layout, which will automatically align widgets to the top and centre.

```
from guizero import App, Picture

app = App(title="smartKey", width=800, height=800)
    
logo = Picture(app, image="cat.gif")

app.display()
```

Closing as not a bug with guizero.

**Closed by martinohanlon** 2020-06-18 10:20 UTC
Labels: help wanted
