### ISSUE TITLE
Button.bg not working on MacOS X

### ISSUE THREAD

**Issue by bvicaa** [lawsie/guizero#328] opened 2019-08-12 13:55 UTC
For some reason, button.bg = 'some color' command does not work on MacOS X (I tried more different versions of Mac). I also tried all of the 3 different color setting modes: 1) .bg = "red", 2) .bg = "#ff0000" and 3) .bg = (255, 0, 0), none of these had working. When I print the value of the actual background of a button, it says the proper color which is not visible in the gui. So somehow the program knows what color the button should be, but displaying 
![PushButton_issue](https://user-images.githubusercontent.com/50593365/62870235-926d9d00-bd19-11e9-85cb-96aa1eae339c.JPG)
it fails.
Here you can see what is wrong, the button should be yellow: 
https://imgur.com/R2xfX48

**Comment by lawsie** [comment] 2019-08-12 14:00
I can confirm that the code above does successfully generate a yellow button on Windows. It is almost certainly to do with the way that MacOS renders the GUI, which isn't easily controllable. Maybe Martin has some thoughts.

**Comment by bvicaa** [comment] 2019-08-12 14:09
Dear Laura,

Thank you for your fast reply. I created a software with gui using guizero
and some tkinter elements, which software I want to release both for MacOS
and Windows. Since I am using Windows, I did not realize this problem until
I tried my program on MacOS X also, where the only difference was the
button background, which is more or less important for the software usage,
because pressing a button will change the color of the button. I would be
very happy if you could fix this or give me some idea what to do. For
example, textbutton.bg is working properly on MacOS X.

Thanks again, and I hope you can find me a solution!
Regards,
Vica

Laura Sach <notifications@github.com> ezt írta (időpont: 2019. aug. 12., H,
16:00):

**Comment by martinohanlon** [comment] 2019-08-12 19:47
It's not possible to change the colour of a button in macOS. It's one of the things macOS doesnt allow you to do. You also can't change the size of a Button.

There is a thread here https://stackoverflow.com/questions/1529847/how-to-change-the-foreground-or-background-colour-of-a-tkinter-button-on-mac-os which offers some alternatives.

**Comment by martinohanlon** [comment] 2019-08-15 20:28
Closing as not a bug in guizero.

**Closed by martinohanlon** 2019-08-15 20:28 UTC
