### ISSUE TITLE
.destroy() - Not working as I expected.

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#407] opened 2021-02-10 15:01 UTC
**Describe the bug**
When I use `.destroy()` the widget (some) objects are still there?
I would expect all the widget to no longer be there.

_An x*y grid of Button widgets has been created in a Box
This should destroy them all.__
```
    for widget in bottom_box.children:
        widget.destroy()
```
Still has objects in it
```
bottom [guizero.PushButton object, guizero.PushButton object, guizero.PushButton object, guizero.PushButton object, guizero.PushButton object, guizero.PushButton object, guizero.PushButton object]
```
**To Reproduce**
cut down version to show Button, but same for a picture grid too.
https://pastebin.com/R4m40eBA

**Expected behaviour**
I would expect all the widget to no longer be there.

**System information:**
 - OS: Windows10
 - guizero version: v1.1.1 used in Thonny 3.3.3

**Additional context**
This was part of the emoji game in GUI @ FutureLearn.
I extended to have a new grid size randomly created. 
It doesn't work and the none deleted button are still populated with pictures and can be used to match up https://pastebin.com/EQ2Sb7dc if pictures help show it better. (need emojis from https://rpf.io/fl-guis-emojis )

**Comment by aajshaw** [comment] 2021-02-10 16:12
The pastebin link to your code did not seem to be working but I think I managed to find your code. It seems to me that destroying and remaking the Box that contains the Pushbuttons does the trick:
```python
from random import randint
from guizero import App, Box, PushButton, Text
 
def destroy_grids():
    if bottom_emoji_box:
         # Remove each widget in the boxes, this allows the ability to alter the size for next game.
        for widget in bottom_emoji_box.children:
            widget.destroy()
        bottom_emoji_box.destroy()
        #debug
        print(f"bottom {bottom_emoji_box.children}")
 
def setup_grids(width, height):
    global bottom_emoji_box
    bottom_emoji_box = Box(app, layout="grid", align="bottom", width=480, height=320)
     # Generate grids, mirrored in each box.
    for x in range(width):
        for y in range(height):
            print(f"{x}, {y}") # debug grid creation
            pic_button = PushButton(bottom_emoji_box, command=match_emoji, args=[False], grid=[x,y])
    print("Grid created\n")
        
def the_game():
     # Once started disable button and (re)enale the bottom slection area.
     # Game grid dimensions
    width = randint(3,6)
    height = randint(3,4)
     # need to remove all widgets, before we recreate the,
    destroy_grids()
     # Generate Grids
    setup_grids(width, height)
 
def match_emoji(match):
    pass
        
 # The App window
app=App("Game", width=500, height=400)
 
 # Create the boxes
control_box = Box(app, layout="grid")
#bottom_emoji_box = Box(app, layout="grid", align="bottom", width=480, height=320)
bottom_emoji_box = None
 
#control_box
button_play_game = PushButton(control_box, text="Start Game", command=the_game, grid=[1,0])
app.display()

```
The above code creates the bottom_emoji_box in the ```setup_grids``` method and destroys it in the ```destroy_grids``` method if it has been created.

I don't think this is a bug, the Box is holding references to Pushbutton objects after they have been destroyed, but they have not actutally been removed from the Box.

**Comment by bsimmo** [comment] 2021-02-10 17:01
What does destroy() actually do then?

Because some boxes are removed, as can be seen visually when running it.
In the full code with the matching pictures boxes above, it's the same ones
left being on both
They are no longer there.
So it is inconsistent..
Predictable if it happens in two boxes in the same way, a pattern?

To me that's a bug?

**Comment by bsimmo** [comment] 2021-02-10 17:23
fixed links.

**Comment by martinohanlon** [comment] 2021-02-10 18:39
This is highly unlikely to be a bug with guizero. .destroy() makes a direct call to tkinter. 

Note though the destroy does just that it halts the execution of the code and unless managed carefully can leave your application in a non determinate state. This is what I suspect is happening in your application. 

I would recommend that you use .hide() or reset the individual properties of the widgets rather than destroying an recreating.

I thought there was a note in the documentation stating this but right now I can't find it.

**Comment by martinohanlon** [comment] 2021-02-10 18:47
see #365 for another example of .destroy leaving applications in a non-deterministic state

> I thought there was a note in the documentation stating this but right now I can't find it.
#367 is the issue to update documentation to not the consequence of using .destroy

**Comment by bsimmo** [comment] 2021-02-10 19:15
OK, definitely needs more information on it, as destroy to me means destroy
it and remove it. Get rid of all references. (as there is no delete).
This is guizero, not tkinter, so personale expect thing to be easy.

Though you do say this.
"
Also note once an widget has been destroyed it can no longer be used within
an application, so if you wanted to show the win again, the call will fail
because it has been destroyed.
"

How come I am then using some and clicking on them behaves exactly as if
they are there, even as much as setting properties on them.

**Comment by martinohanlon** [comment] 2021-02-10 19:18
@bsimmo Re your particular problem...

I think its because of this... You are trying to destroy the widget while iterating through the list of widgets.

```python
    for widget in top_emoji_box.children:
        widget.destroy()
```

This is going to result in some strange behaviour. You are removing an item in a list at the same time as removing an item from the list.

Try this code:

```python
my_list = [1,2,3,4,5,6,7,8,9,0]
for element in my_list:
    my_list.remove(element)
print(my_list)
```

You may expect it to remove all the items, but it doesnt! At the end of this program `my_list` will be `[2, 4, 6, 8, 0]`

I "think" the easiest way to fix this would be to iterate through a copy of the list e.g.

```python
    for widget in top_emoji_box.children.copy():
        widget.destroy()
    for widget in bottom_emoji_box.children.copy():
        widget.destroy()
```

I have tested the program and your debug statements now return blank lists. Whether the program works has you expect is a different question!?

Closing as not a bug with guizero.

**Closed by martinohanlon** 2021-02-10 19:18 UTC
Labels: bug

**Comment by bsimmo** [comment] 2021-02-10 19:51
Many thanks for the added explanation :-)
That makes sense. 

P. S. It was opened as a bug as there wasn't a query option presented in the github template and it made me think bug and auto gave it bug tag.
I would have preferred question or unsure. 

I'll get back altering the program now I understand destroy better and also my error in thinking 👍

I'll also look at a hide way of doing it.

Just had a though.

**Comment by martinohanlon** [comment] 2021-02-10 19:56
This isn't a great place to raise questions and queries. I am sometimes the
only person who monitors these issues and it's not part of my job.

I usually recommend the raspberrypi forum as a good place to go. You will
usually find a lot of people will to help.

**Comment by bsimmo** [comment] 2021-02-10 19:59
I usually do, it basically just Scotty that answers there.
But I did think it was a specific problem with .destroy() at the time. I just wouldn't normally tag it as bug until it was confirmed.
