### ISSUE TITLE
Slider hide/show bug

### ISSUE THREAD

**Issue by bgiobbe** [lawsie/guizero#479] opened 2023-07-15 00:11 UTC
**Slider.show() doesn't show the slider**

After being hidden, the Slider widget does not become visible when its show() method is called, unless the window is resized.

**To Reproduce**

Example code: [bug1.py.txt](https://github.com/lawsie/guizero/files/12059480/bug1.py.txt)

```
from guizero import App, PushButton, Slider

def toggle():
    if slider.visible:
        slider.hide()
        button.text = 'Show'
    else:
        slider.show()
        button.text = 'Hide'

app = App(title='Slider show/hide bug')
button = PushButton(app, align='top', text='Hide', command=toggle)
slider = Slider(app, start=0, end=100, width=300)
app.display()
```

Steps to reproduce the behaviour:

1. Run attached program "bug1.py" (after removing .txt). The screen shows a button and a slider.
2. Click the Hide button. The slider should hide, and it does.
3. Click the Show button. The slider should show, but it doesn't.
4. Click the Hide button again. The slider should hide if it were visible, but first it shows while the button is held down.
5. Click the Show button again, then resize the window. The slider appears after the window is resized.

**Expected behavior**

The slider should appear when the Show button is clicked, without having to resize the window.

**System information:**

 - OS: MacOS 12.6.7 (21G651)
 - guizero version: 1.4.0
 - Tk version: 8.6.13 (tcl-tk installed with HomeBrew)

**Comment by martinohanlon** [comment] 2023-07-15 05:51
Thanks for raising a really well described issue ❤️. It really helps.

Out of interest does putting an `app.update()` into the `toggle` function resolve the issue e.g.

```python
def toggle():
    if slider.visible:
        slider.hide()
        button.text = 'Show'
    else:
        slider.show()
        button.text = 'Hide'
    app.update()
```

**Comment by martinohanlon** [comment] 2023-07-15 07:45
I cant reproduce the issue on Windows 11 or Linux (Raspberry Pi Desktop).

I suspect this is a macos / tkinter related issue. I'll test on an older mac to see if this is an issue introduced with the later version or one that has existed for a while.

**Comment by bgiobbe** [comment] 2023-07-15 14:32
@martinohanlon  Adding app.update() does not resolve it.
I also tried slider.focus() in the else-block. That did not resolve it either.
However, putting the slider in a Box resolves it. But if I then hide/show the box instead of the slider, the button disappears too!
```
from guizero import App, Box, PushButton, Slider

def toggle():
    if slider.visible:
        slider.hide()
        button.text = 'Show'
    else:
        slider.show()
        button.text = 'Hide'

app = App(title='Slider show/hide bug')
button = PushButton(app, align='top', text='Hide', command=toggle)
box = Box(app, width=400, height=50, border=True)
slider = Slider(box, start=0, end=100, width=300)
app.display()
```
I also suspect it's a MacOS/tkinterr/tk issue. I need to rewrite it with tkinter instead of guizero and see if it behaves the same.

**Comment by martinohanlon** [comment] 2023-07-15 15:13
I cant reproduce the error on: 
- macos 12.6.3 (21G419)
- tcl version 8.6.8
- python 3.9.2
- guizero 1.4.0

https://github.com/lawsie/guizero/assets/2329501/6ab329d6-b363-49e8-aa8a-c7f52862b2a6

I am going to update to macos 12.6.7 and python 3.11.4 and see if that makes a difference

**Comment by bgiobbe** [comment] 2023-07-15 18:16
I have tried it in Python 3.10.11 and 3.11.4. Can you update TCL/TK?

**Comment by bgiobbe** [comment] 2023-07-15 20:53
I rewrote it with Tkinter:
```
from tkinter import *
from tkinter.ttk import *
   
def toggle():
    if button_label.get() == 'Hide':
        button_label.set('Show')
        slider.pack_forget()
    else:
        button_label.set('Hide')
        slider.pack(side='top')

root = Tk()
root.title("Slider show/hide bug | tkinter")
root.geometry('400x200')
button_label = StringVar()
button_label.set('Hide')
button = Button(root, textvariable=button_label, command=toggle)
slider = Scale(root, from_=1.0, to=100.0, length=300)
button.pack(side='top')
slider.pack(side='top')
root.mainloop()
```
This version doesn't show the slider (Scale) until the mouse-pointer moves off the button (after clicking Show).

https://github.com/lawsie/guizero/assets/1522307/9913a356-2f25-457c-8ca9-99a39365fd34

**Comment by martinohanlon** [comment] 2023-07-16 15:13
I cant reproduce this issue with "standard released" versions of macos and Python.

I update macos to 12.6.7 (21G651) and tried the following:

- macos 12.6.3 (21G419)
- python 3.9.2
- tcl version 8.6.8

I then updated Python to the latest stable version and tried with:

- macos 12.6.3 (21G419)
- python 3.11.4
- tcl version 8.6.12 (which was installed with python 3.11.4)

As far as I can tell guizero acts as it should.

https://github.com/lawsie/guizero/assets/2329501/887d0d83-9fef-4caf-8d73-97563ab3472d

@bgiobbe you say the machine you are using is running tk version 8.6.13. This is at odds with the version distributed with the latest version of Python. The only thing I can think of doing is uninstalling Python and Tk and installing new from the distribution on https://www.python.org/downloads/.

Sorry I cant be more help.

**Comment by bgiobbe** [comment] 2023-07-16 16:40
Thanks. I'll try going back to TCL 8.6.12.   
  
  

  
  
>

**Comment by bgiobbe** [comment] 2023-07-16 18:24
I couldn't find an installer for TCL/TK 8.6.12, so I uninstalled python, python-tk, and tcl-tk from HomeBrew, then installed Python with installer from python.org. This installed TCL/TK 8.6.12. The bug is resolved in this version! Yay!
Apparently a bug in showing and hiding was introduced in TK 8.6.13.
Thank you for your help!

**Comment by martinohanlon** [comment] 2023-07-18 08:38
I have removed the bug as the issue is resolved and will close the issue but there is a cautionary tale about the impact tk/tcl version change can have. 

If it becomes an issue would recommend we have noted supported versions.

**Closed by martinohanlon** 2023-07-18 08:38 UTC
