### ISSUE TITLE
MacOS does not allow right click on a PushButton

### ISSUE THREAD

**Issue by bvicaa** [lawsie/guizero#330] opened 2019-08-15 11:43 UTC
I need 2 different event for using a PushButton on Mac. However, I realized that right click event does not work on MacBook, even the alternative Ctrl+Left Click. How to use 2 different command (left click/right click) when using a PushButton? Is there any alternative event on a button than left and right click, e.g. double click or something else?

**Comment by martinohanlon** [comment] 2019-08-15 20:28
tkinter supports a double click event on a widget - https://stackoverflow.com/questions/27262580/tkinter-binding-mouse-double-click

You can use the lower level tkinter functionality within guizero - https://lawsie.github.io/guizero/usingtk/

Something like:

```python
my_widget.tk.bind('<Double-Button-1>', my_function)
```

Closing as not a bug with guizero.

**Closed by martinohanlon** 2019-08-15 20:28 UTC
